### ISSUE TITLE
Release a separate get version

### ISSUE THREAD

**Issue by VladShcherbin** [tsuyoshiwada/dot-wild#12]
Hey

I've got a small request. I wanted to find a small library that can get nested properties with array support using `*`. I checked other libraries like [dlv](https://github.com/developit/dlv) or [dot-prop](https://github.com/sindresorhus/dot-prop), which are small (less than 1 kb), but they are lacking some features that I need.

I like how `dot-wild` works, but it's a bit heavy for me ([almost 10kb](https://bundlephobia.com/result?p=dot-wild@3.0.0)) because it's using `clone` package for setters, which is more than 7kb itself.

So I thought, maybe you can release a separate version with only getters? It will be small (under 2kb I guess) and is a really good alternative for above ones.

**Comment by VladShcherbin** [comment]
Or maybe it's possible to swap `clone` package with something else so `dot-wild` could drop some size.

**Comment by tsuyoshiwada** [comment]
@VladShcherbin I agree that dot-wild package file size is large.

I tried using the `clone-deep` package, but it seemed to work perfectly :+1:

First, change from `clone` to `clone-deep`. After that, I will try to create a package specifically for Getter like `dot-wild-tiny`.

**Comment by VladShcherbin** [comment]
@tsuyoshiwada thank you, this will be really great 🎉

**Comment by tsuyoshiwada** [comment]
@VladShcherbin First we released `v3.0.1` changed to `clone-deep` :smiley:

Once package creation for Getter is completed, I will comment here again :muscle:

**Comment by VladShcherbin** [comment]
@tsuyoshiwada [here](https://bundlephobia.com/result?p=dot-wild@3.0.1) you can see instant reward in size 👍

**Comment by tsuyoshiwada** [comment]
@VladShcherbin Thx!! About 34.04% file size reduction ... :tada:

**Comment by VladShcherbin** [comment]
Yep, dropped 66% of size (from 9.4kb to 3.2kb gzipped) with just one line changed, how cool is that 😄

**Comment by tsuyoshiwada** [comment]
@VladShcherbin Released [dot-wild-tiny](https://github.com/tsuyoshiwada/dot-wild-tiny) which only `get` :tada:
The file size was dropped up to 1/3 :+1:

**Comment by VladShcherbin** [comment]
@tsuyoshiwada nice. Maybe it's possible to add `forEach`, `map` methods there? They are very useful when you want to get value with it's path or iterate over them.

**Comment by VladShcherbin** [comment]
I also found out that you forgot to commit/publish new `yarn.lock` files both for `dot-wild` and `dot-wild-tiny`.

**Comment by wadackel** [comment]
Hi @VladShcherbin We added `get`, `forEach` and `map` methods respectively :+1:

**Comment by vladshcherbin** [comment]
@tsuyoshiwada huge thank you. That's all I needed ❤️
