### ISSUE TITLE
Add possibility to iterate only arrays when wildcard is used

### ISSUE THREAD

**Issue by VladShcherbin** [tsuyoshiwada/dot-wild#8]
```js
const data = {
  name: 'James'
}

const anotherData = [1, 2, 3]

console.log(dot.get(data, '*'))
```

If wildcard is used here, it will iterate over the `data` object fields and return their values. I need it to iterate only over arrays and return the values of the array. So, in the above example I want it to return `null`. Same search on `anotherData` would return array values (`[1, 2, 3]`).

Is this possible to add to the library?

Thanks

**Comment by tsuyoshiwada** [comment]
Hi @VladShcherbin, Thanks for Issues !

I want to use wildcards to operate regardless of objects or arrays.
It is due to higher versatility.

I am sorry, but it seems to be unnecessary to add it as a library function :cry:

**Comment by VladShcherbin** [comment]
@tsuyoshiwada I understand that it iterates both objects and arrays for higher versatility, but there are use cases like mine which currently can't be solved and you'll have to write your own library for that.

Since there is already a great library, I thought maybe it can be added here. For example, if you provide third argument as an options array:

```js
dot.get(data, '*', { default: 'no data', iterateObjects: false })
```

**Comment by tsuyoshiwada** [comment]
@VladShcherbin That makes sense :+1:
I misunderstood that it changed behavior of the `get` method.
I think that the content you proposal is good.

However there are points to worry about.

If you add an option with the `get` method, how do you like how` set` or `remove` methods are behaving?

**Comment by VladShcherbin** [comment]
@tsuyoshiwada in my project I only need this for getters - `forEach`, `get`, maybe `map` methods.

Maybe it's possible to add this feature to getters first and if someone will also need this for setters (and removals), add it later.

It's easier to add features when you know the use cases for them instead of thinking of possible usage examples for other methods. I can probably thinks of some examples for other methods, but all of them will be fictional, not real ones. What do you think?

**Comment by tsuyoshiwada** [comment]
@VladShcherbin I agree with you about that.
I'd like to implement options for `forEach`, `map`, `get`.
I will let you know here again as soon as the implementation is over :smiley:

Thanks !

**Comment by VladShcherbin** [comment]
@tsuyoshiwada yeah, it's working for me. Thank you!

**Comment by tsuyoshiwada** [comment]
@VladShcherbin Thank you for checking! Released a version that removed `alpha` :tada:
